name: Reports

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Run Flutter analyze and test
    permissions:
      id-token: write
      contents: read
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: "12.x"
      - uses: subosito/flutter-action@v2.12.0
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test --coverage
      - run: mkdir reports
      - run: flutter test --machine --reporter=json > reports/test-results.json
      - uses: dorny/test-reporter@v1.7.0
        with:
          name: 'Unit Test results'
          path: 'reports/test-results.json'
          reporter: 'flutter-json'
          token: ${{ github.token }}
      - uses: VeryGoodOpenSource/very_good_coverage@v2.2.0
        with:
          min_coverage: 70